"""added_merknad_field_for blocked_time

Revision ID: 3000bfc6da03
Revises: 5099572b9811
Create Date: 2015-06-11 12:44:24.888224

"""

# revision identifiers, used by Alembic.
revision = '3000bfc6da03'
down_revision = 'dbf20046b3b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocked_time_intervals', sa.Column('note', sa.String(), nullable=True))
    op.add_column('weekly_blocked_times', sa.Column('note', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_blocked_times', 'note')
    op.drop_column('blocked_time_intervals', 'note')
    ### end Alembic commands ###
