"""added new fields for application

Revision ID: 41e40fd528c6
Revises: 3000bfc6da03
Create Date: 2015-09-21 13:15:51.529749

"""

# revision identifiers, used by Alembic.
revision = '41e40fd528c6'
down_revision = '3000bfc6da03'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('requested_accessibility', postgresql.HSTORE(), nullable=True))
    op.add_column('applications', sa.Column('requested_amenities', postgresql.HSTORE(), nullable=True))
    op.add_column('applications', sa.Column('requested_equipment', postgresql.HSTORE(), nullable=True))
    op.add_column('applications', sa.Column('requested_suitability', postgresql.HSTORE(), nullable=True))
    op.add_column('applications', sa.Column('accessibility', postgresql.HSTORE(), nullable=True))
    op.add_column('applications', sa.Column('amenities', postgresql.HSTORE(), nullable=True))
    op.add_column('applications', sa.Column('equipment', postgresql.HSTORE(), nullable=True))
    op.add_column('applications', sa.Column('suitability', postgresql.HSTORE(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'requested_suitability')
    op.drop_column('applications', 'requested_equipment')
    op.drop_column('applications', 'requested_amenities')
    op.drop_column('applications', 'requested_accessibility')
    op.drop_column('applications', 'suitability')
    op.drop_column('applications', 'equipment')
    op.drop_column('applications', 'amenities')
    op.drop_column('applications', 'accessibility')
    ### end Alembic commands ###
