"""added comment

Revision ID: 302c467502a1
Revises: 477fa4b88fe
Create Date: 2015-09-23 14:06:14.143417

"""

# revision identifiers, used by Alembic.
revision = '302c467502a1'
down_revision = '477fa4b88fe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('comment', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'comment')
    ### end Alembic commands ###
