"""empty message

Revision ID: dbf20046b3b
Revises: 53d9b4913a0
Create Date: 2015-06-17 09:22:47.352693

"""

# revision identifiers, used by Alembic.
revision = 'dbf20046b3b'
down_revision = '53d9b4913a0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy import *

def upgrade():

    metadata = MetaData()

    settings = Table('settings',
                     metadata,
                     Column('key', sa.String(), primary_key=True, nullable=False),
                     Column('value', sa.String(), nullable=True),
                     Column('type', sa.Enum('bool', 'date', 'int', name='settings_types_enums'), nullable=False)
    )

    op.bulk_insert(settings,
                   [
                       {'key': 'repeating_booking_enddate', 'value': '', 'type': 'date'},
                       {'key': 'single_booking_enddate', 'value': '', 'type': 'date'}
                   ]
    )

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
