"""added_table_settings

Revision ID: 53d9b4913a0
Revises: 5099572b9811
Create Date: 2015-06-02 08:33:58.966437

"""

# revision identifiers, used by Alembic.
revision = '53d9b4913a0'
down_revision = '5099572b9811'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

def upgrade():
    settings = op.create_table('settings',
                    sa.Column('key', sa.String(), primary_key=True, nullable=False, autoincrement=False),
                    sa.Column('value', sa.String(), nullable=True),
                    sa.Column('type', sa.Enum('bool', 'date', 'int', name='settings_types_enums'), nullable=False)
    )

    op.bulk_insert(settings,
                   [
                       {'key': 'repeating_booking_allowed', 'value': 'false', 'type': 'bool'},
                       {'key': 'single_booking_allowed', 'value': 'true', 'type': 'bool'},
                       {'key': 'strotime_booking_allowed', 'value': 'false', 'type': 'bool'},
                       {'key': 'repeating_booking_deadline', 'value': '', 'type': 'date'}
                   ]
    )

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    ENUM(name="settings_types_enums").drop(op.get_bind(), checkfirst=False)
    ### end Alembic commands ###


