"""added_rammetid_allowed

Revision ID: 435e5a797908
Revises: 4296c837b54c
Create Date: 2016-07-10 19:05:45.473132

"""

# revision identifiers, used by Alembic.
revision = '435e5a797908'
down_revision = '4296c837b54c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('rammetid_allowed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'rammetid_allowed')
    ### end Alembic commands ###
