"""added facilitators

Revision ID: 52fd8e9e8e68
Revises: 41523d838a49
Create Date: 2015-09-23 12:16:34.663534

"""

# revision identifiers, used by Alembic.
revision = '52fd8e9e8e68'
down_revision = '41523d838a49'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilities', sa.Column('facilitators', postgresql.HSTORE(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facilities', 'facilitators')
    ### end Alembic commands ###
