"""added_relevant_for_tkn

Revision ID: 1a08b9e1f753
Revises: 52923cf8bab3
Create Date: 2015-06-22 12:20:34.128969

"""

# revision identifiers, used by Alembic.
revision = '1a08b9e1f753'
down_revision = '52923cf8bab3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('relevant_tkn', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisations', 'relevant_tkn')
    ### end Alembic commands ###
