"""added_extra_fields_on_organisation

Revision ID: 424f4e48b5ad
Revises: 1a08b9e1f753
Create Date: 2015-06-23 11:59:24.819429

"""

# revision identifiers, used by Alembic.
revision = '424f4e48b5ad'
down_revision = '1a08b9e1f753'


from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('local_email_address', sa.String(length=150), nullable=True))
    op.add_column('organisations', sa.Column('tilholdssted_address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'organisations', 'addresses', ['tilholdssted_address_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organisations', type_='foreignkey')
    op.drop_column('organisations', 'tilholdssted_address_id')
    op.drop_column('organisations', 'local_email_address')
    ### end Alembic commands ###
