"""Added internal notes

Revision ID: 52923cf8bab3
Revises: e43880d1328
Create Date: 2015-06-11 12:29:57.051020

"""

# revision identifiers, used by Alembic.
revision = '52923cf8bab3'
down_revision = 'e43880d1328'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations_internal_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('auth_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organisations_internal_notes')
    ### end Alembic commands ###
